language: python

python:
  - "3.7"

services:
  - docker

before_install:
  - pip install selene --pre
  - sh selenoid_start.sh

script:
  - pytest --browser_ver=83.0 tests/
  - pytest --browser=firefox --browser_ver=77.0 tests/

